export const REGIONS = [
  'Addis Ababa',
  'Afar',
  'Amhara',
  'Benishangul-Gumuz',
  'Central Ethiopia',
  'Dire Dawa',
  'Gambela',
  'Harari',
  'Oromia',
  'Sidama',
  'Somali',
  'South Ethiopia',
  'South West Ethiopia',
  'Tigray',
];

export const CITIES = [
  'Addis Ababa',
  'Adama',
  'Bahir Dar',
  'Debre Birhan',
  'Dessie',
  'Gondar',
  'Hawassa',
  'Jimma',
  'Mekelle',
  'Dire Dawa',
  'Jigjiga',
  'Harar',
  'Arba Minch',
  'Shashamane',
  'Bishoftu',
  'Nekemte',
  'Asella',
  'Ambo',
  'Debre Markos',
  'Kombolcha',
  'Semera',
  'Asaita',
  'Gode',
  'Bonga',
  'Sodo',
  'Shire',
  'Adigrat',
  'Axum',
  'Butajira',
  'Hosaina',
  'Dembidolo',
  'Hosaena',
  'Arsi Negele',
  'Metu',
  'Yirgalem',
  'Bure',
  'Finote Selam',
  'Woliso',
  'Bedele',
];

export const REGION_CITIES = {
  'Addis Ababa': ['Addis Ababa'],
  'Afar': ['Semera', 'Asaita', 'Gewane', 'Dubti', 'Chifra'],
  'Amhara': ['Bahir Dar', 'Gondar', 'Dessie', 'Debre Birhan', 'Debre Markos', 'Kombolcha', 'Woldia', 'Finote Selam', 'Bure'],
  'Benishangul-Gumuz': ['Asosa', 'Mendida', 'Kamashi'],
  'Central Ethiopia': ['Hosaina', 'Butajira', 'Bule Hora', 'Arsi Negele'],
  'Dire Dawa': ['Dire Dawa'],
  'Gambela': ['Gambela', 'Tepi', 'Metu'],
  'Harari': ['Harar'],
  'Oromia': ['Adama', 'Jimma', 'Bishoftu', 'Shashamane', 'Nekemte', 'Asella', 'Ambo', 'Bako', 'Woliso', 'Arsi Negele', 'Dessie'],
  'Sidama': ['Hawassa', 'Yirgalem'],
  'Somali': ['Jigjiga', 'Gode', 'Degehabur', 'Kibre Mengist'],
  'South Ethiopia': ['Arba Minch', 'Sodo', 'Hosaena'],
  'South West Ethiopia': ['Bonga', 'Mizan Teferi', 'Dilla'],
  'Tigray': ['Mekelle', 'Shire', 'Adigrat', 'Axum', 'Hawzen'],
};

export const JOB_CATEGORIES = [
  'IT & Software Development',
  'Healthcare & Medical',
  'Finance, Banking & Accounting',
  'Engineering & Construction',
  'Marketing, Sales & Business Development',
  'Education & Training',
  'Agriculture & Forestry',
  'Administration & Human Resources',
  'Customer Service & Support',
  'Creative, Design & Media',
];
