export const REGIONS = [
  'Addis Ababa',
  'Afar',
  'Amhara',
  'Benishangul-Gumuz',
  'Central Ethiopia',
  'Dire Dawa',
  'Gambela',
  'Harari',
  'Oromia',
  'Sidama',
  'Somali',
  'South Ethiopia',
  'South West Ethiopia',
  'Tigray',
];

export const CITIES = [
  'Addis Ababa',
  'Adama',
  'Bahir Dar',
  'Debre Birhan',
  'Dessie',
  'Gondar',
  'Hawassa',
  'Jimma',
  'Mekelle',
  'Dire Dawa',
  'Jigjiga',
  'Harar',
  'Arba Minch',
  'Shashamane',
  'Bishoftu',
];

export const REGION_CITIES = {
  'Addis Ababa': ['Addis Ababa'],
  'Afar': ['Semera', 'Asaita'],
  'Amhara': ['Bahir Dar', 'Gondar', 'Dessie', 'Debre Birhan', 'Debre Markos', 'Kombolcha'],
  'Benishangul-Gumuz': ['Asosa'],
  'Central Ethiopia': ['Hosaina', 'Butajira'],
  'Dire Dawa': ['Dire Dawa'],
  'Gambela': ['Gambela'],
  'Harari': ['Harar'],
  'Oromia': ['Adama', 'Jimma', 'Bishoftu', 'Shashamane', 'Nekemte', 'Asella', 'Ambo'],
  'Sidama': ['Hawassa'],
  'Somali': ['Jigjiga', 'Gode'],
  'South Ethiopia': ['Arba Minch', 'Sodo'],
  'South West Ethiopia': ['Bonga'],
  'Tigray': ['Mekelle', 'Shire', 'Adigrat', 'Axum'],
};

export const JOB_CATEGORIES = [
  'IT & Software Development',
  'Healthcare & Medical',
  'Finance, Banking & Accounting',
  'Engineering & Construction',
  'Marketing, Sales & Business Development',
  'Education & Training',
  'Agriculture & Forestry',
  'Administration & Human Resources',
  'Customer Service & Support',
  'Creative, Design & Media',
];
